sudo: false
cache: yarn
language: node_js
env:
  global:
  - NODE_ENV='test'
  - DOCKER_PASSWORD='22TZ5OTNLCMSKQVHWPX99P9ZMQ5G2UBTB8UDL508OHSKAE6LEWCB5T2XA65OASTU'
  - DOCKER_USER='jmrodrigueza+guithub'
before_install:
- cd ./$SERVICE
- nvm install
- nvm use
- node --version
before_script:
- SERVICE=$SERVICE make ensure-dependencies
- sleep 10
script:
- make qa
- make brand
- make package

matrix:
  include:
  - env: SERVICE=recipes-api
    services:
    - docker
  - env: SERVICE=recipes-crawler
    services:
    - docker
  - env: SERVICE=recipes-id-generator
    services:
    - docker